[2024-12-19T17:08:42.071+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:07:08+00:00 [queued]>
[2024-12-19T17:08:42.078+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:07:08+00:00 [queued]>
[2024-12-19T17:08:42.079+0900] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-19T17:08:42.093+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-19 08:07:08+00:00
[2024-12-19T17:08:42.098+0900] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2024-12-19T17:08:42.102+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-19T08:07:08+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpv4vyck08']
[2024-12-19T17:08:42.105+0900] {standard_task_runner.py:85} INFO - Job 4: Subtask post_crawl
[2024-12-19T17:08:42.147+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:07:08+00:00 [running]> on host 2620e3d1ef1d
[2024-12-19T17:08:42.217+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T08:07:08+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T08:07:08+00:00'
[2024-12-19T17:08:42.219+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-19 17:08:42
[2024-12-19T17:08:42.219+0900] {logging_mixin.py:151} INFO - 점핏 종료 시간: 2024-12-19 17:08:42
[2024-12-19T17:08:52.229+0900] {logging_mixin.py:151} INFO - 원티드 시작 시간: 2024-12-19 17:08:52
[2024-12-19T17:08:52.248+0900] {credentials.py:1254} INFO - Found credentials in shared credentials file: /code/.aws/credentials
[2024-12-19T17:08:52.559+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:08:52.730+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:08:52.803+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:08:52.877+0900] {logger.py:11} INFO - There is no [linux64] chromedriver "131.0.6778.204" for browser google-chrome "131.0.6778" in cache
[2024-12-19T17:08:52.878+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:08:53.033+0900] {logger.py:11} INFO - WebDriver version 131.0.6778.204 selected
[2024-12-19T17:08:53.038+0900] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T17:08:53.040+0900] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T17:08:53.149+0900] {logger.py:11} INFO - Driver downloading response is 200
[2024-12-19T17:08:53.408+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:08:53.592+0900] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204]
[2024-12-19T17:08:53.936+0900] {logging_mixin.py:151} INFO - 원티드 종료 시간: 2024-12-19 17:08:53
[2024-12-19T17:08:53.937+0900] {logging_mixin.py:151} INFO - 인크루트 시작 시간: 2024-12-19 17:08:53
[2024-12-19T17:08:54.510+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:08:54.581+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:08:54.646+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:08:54.717+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:08:54.848+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1942, in post_main
    incruit_crawling()
  File "/code/plugins/post_crawling.py", line 623, in incruit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c74f34d8fa <unknown>
#1 0x55c74ee5ed20 <unknown>
#2 0x55c74ee96438 <unknown>
#3 0x55c74ee91f96 <unknown>
#4 0x55c74eeddd86 <unknown>
#5 0x55c74eedd3d6 <unknown>
#6 0x55c74eed1893 <unknown>
#7 0x55c74eea030d <unknown>
#8 0x55c74eea132e <unknown>
#9 0x55c74f31a00b <unknown>
#10 0x55c74f31df97 <unknown>
#11 0x55c74f30671c <unknown>
#12 0x55c74f31eb17 <unknown>
#13 0x55c74f2eb6cf <unknown>
#14 0x55c74f33c6b8 <unknown>
#15 0x55c74f33c880 <unknown>
#16 0x55c74f34c776 <unknown>
#17 0x7f78dd9bbea7 start_thread

[2024-12-19T17:08:54.870+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241219T080708, start_date=20241219T080842, end_date=20241219T080854
[2024-12-19T17:08:54.889+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task post_crawl (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55c74f34d8fa <unknown>
#1 0x55c74ee5ed20 <unknown>
#2 0x55c74ee96438 <unknown>
#3 0x55c74ee91f96 <unknown>
#4 0x55c74eeddd86 <unknown>
#5 0x55c74eedd3d6 <unknown>
#6 0x55c74eed1893 <unknown>
#7 0x55c74eea030d <unknown>
#8 0x55c74eea132e <unknown>
#9 0x55c74f31a00b <unknown>
#10 0x55c74f31df97 <unknown>
#11 0x55c74f30671c <unknown>
#12 0x55c74f31eb17 <unknown>
#13 0x55c74f2eb6cf <unknown>
#14 0x55c74f33c6b8 <unknown>
#15 0x55c74f33c880 <unknown>
#16 0x55c74f34c776 <unknown>
#17 0x7f78dd9bbea7 start_thread
; 136)
[2024-12-19T17:08:54.921+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-19T17:08:54.941+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
