[2024-12-20T17:06:21.965+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T07:58:36+00:00 [queued]>
[2024-12-20T17:06:21.976+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T07:58:36+00:00 [queued]>
[2024-12-20T17:06:21.976+0900] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2024-12-20T17:06:21.990+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-20 07:58:36+00:00
[2024-12-20T17:06:21.995+0900] {standard_task_runner.py:57} INFO - Started process 1681 to run task
[2024-12-20T17:06:21.997+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-20T07:58:36+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmp2rm350oj']
[2024-12-20T17:06:22.001+0900] {standard_task_runner.py:85} INFO - Job 6: Subtask post_crawl
[2024-12-20T17:06:22.044+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T07:58:36+00:00 [running]> on host 8b6312293dda
[2024-12-20T17:06:22.120+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T07:58:36+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T07:58:36+00:00'
[2024-12-20T17:06:22.120+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-20 17:06:22
[2024-12-20T17:06:22.212+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-20T17:06:22.275+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T17:06:22.358+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T17:06:22.431+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-20T17:06:22.465+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1973, in post_main
    jumpit_crawling()
  File "/code/plugins/post_crawling.py", line 171, in jumpit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x5653aebbb8fa <unknown>
#1 0x5653ae6ccd20 <unknown>
#2 0x5653ae70a4c7 <unknown>
#3 0x5653ae704e8f <unknown>
#4 0x5653ae6fff96 <unknown>
#5 0x5653ae74bd86 <unknown>
#6 0x5653ae74b3d6 <unknown>
#7 0x5653ae73f893 <unknown>
#8 0x5653ae70e30d <unknown>
#9 0x5653ae70f32e <unknown>
#10 0x5653aeb8800b <unknown>
#11 0x5653aeb8bf97 <unknown>
#12 0x5653aeb7471c <unknown>
#13 0x5653aeb8cb17 <unknown>
#14 0x5653aeb596cf <unknown>
#15 0x5653aebaa6b8 <unknown>
#16 0x5653aebaa880 <unknown>
#17 0x5653aebba776 <unknown>
#18 0x7f52fdaefea7 start_thread

[2024-12-20T17:06:22.476+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241220T075836, start_date=20241220T080621, end_date=20241220T080622
[2024-12-20T17:06:22.497+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task post_crawl (Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x5653aebbb8fa <unknown>
#1 0x5653ae6ccd20 <unknown>
#2 0x5653ae70a4c7 <unknown>
#3 0x5653ae704e8f <unknown>
#4 0x5653ae6fff96 <unknown>
#5 0x5653ae74bd86 <unknown>
#6 0x5653ae74b3d6 <unknown>
#7 0x5653ae73f893 <unknown>
#8 0x5653ae70e30d <unknown>
#9 0x5653ae70f32e <unknown>
#10 0x5653aeb8800b <unknown>
#11 0x5653aeb8bf97 <unknown>
#12 0x5653aeb7471c <unknown>
#13 0x5653aeb8cb17 <unknown>
#14 0x5653aeb596cf <unknown>
#15 0x5653aebaa6b8 <unknown>
#16 0x5653aebaa880 <unknown>
#17 0x5653aebba776 <unknown>
#18 0x7f52fdaefea7 start_thread
; 1681)
[2024-12-20T17:06:22.532+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T17:06:22.555+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
