[2024-12-19T09:08:47.084+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.link_crawl manual__2024-12-19T00:08:24+00:00 [queued]>
[2024-12-19T09:08:47.091+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.link_crawl manual__2024-12-19T00:08:24+00:00 [queued]>
[2024-12-19T09:08:47.092+0900] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-12-19T09:08:47.106+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): link_crawl> on 2024-12-19 00:08:24+00:00
[2024-12-19T09:08:47.108+0900] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2024-12-19T09:08:47.111+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'link_crawl', 'manual__2024-12-19T00:08:24+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpnmp1tof1']
[2024-12-19T09:08:47.113+0900] {standard_task_runner.py:85} INFO - Job 7: Subtask link_crawl
[2024-12-19T09:08:47.150+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.link_crawl manual__2024-12-19T00:08:24+00:00 [running]> on host 2da4244d8972
[2024-12-19T09:08:47.213+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='link_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T00:08:24+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T00:08:24+00:00'
[2024-12-19T09:08:47.214+0900] {logging_mixin.py:151} INFO - 인크루트 시작 시간: 2024-12-19 09:08:47
[2024-12-19T09:08:47.214+0900] {logging_mixin.py:151} INFO - /code/plugins/incruit
[2024-12-19T09:12:41.018+0900] {logging_mixin.py:151} INFO - 인크루트 종료 시간: 2024-12-19 09:12:41
[2024-12-19T09:12:46.023+0900] {logging_mixin.py:151} INFO - 잡코리아 시작 시간: 2024-12-19 09:12:46
[2024-12-19T09:12:46.039+0900] {credentials.py:1254} INFO - Found credentials in shared credentials file: /code/.aws/credentials
[2024-12-19T09:12:46.511+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T09:12:46.730+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T09:12:46.810+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T09:12:46.883+0900] {logger.py:11} INFO - There is no [linux64] chromedriver "131.0.6778.204" for browser google-chrome "131.0.6778" in cache
[2024-12-19T09:12:46.884+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T09:12:47.034+0900] {logger.py:11} INFO - WebDriver version 131.0.6778.204 selected
[2024-12-19T09:12:47.036+0900] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T09:12:47.037+0900] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
[2024-12-19T09:12:47.147+0900] {logger.py:11} INFO - Driver downloading response is 200
[2024-12-19T09:12:47.581+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T09:12:47.776+0900] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204]
[2024-12-19T09:12:48.740+0900] {logging_mixin.py:151} INFO - S3에서 기존 링크를 로드했습니다. 총 52개의 링크.
[2024-12-19T09:12:48.740+0900] {logging_mixin.py:151} INFO - 검색 키워드: 데이터 엔지니어 (DE)
[2024-12-19T09:19:11.737+0900] {local_task_job_runner.py:274} WARNING - Recorded pid 1685 does not match the current pid 101
[2024-12-19T09:19:11.738+0900] {process_utils.py:131} INFO - Sending 15 to group 101. PIDs of all processes in the group: [166, 172, 181, 182, 203, 212, 279, 289, 301, 313, 333, 351, 358, 1695, 202, 101]
[2024-12-19T09:19:11.739+0900] {process_utils.py:86} INFO - Sending the signal 15 to group 101
[2024-12-19T09:19:11.740+0900] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-19T09:19:11.753+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/link_crawling.py", line 950, in main
    #jobkorea_link()
  File "/code/plugins/link_crawling.py", line 298, in jobkorea_link
    scrape_links()
  File "/code/plugins/link_crawling.py", line 290, in scrape_links
    new_links = scrape_links_for_keyword(keyword, keyword_code, existing_links, bucket_name)
  File "/code/plugins/link_crawling.py", line 233, in scrape_links_for_keyword
    time.sleep(7)  # 페이지 로딩 대기
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1632, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-19T09:19:11.780+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=link_crawl, execution_date=20241219T000824, start_date=20241219T001908, end_date=20241219T001911
[2024-12-19T09:19:11.880+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task link_crawl (Task received SIGTERM signal; 101)
[2024-12-19T09:19:11.897+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=166, status='terminated', started='09:12:47') (166) terminated with exit code None
[2024-12-19T09:19:12.083+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=358, status='terminated', started='09:12:50') (358) terminated with exit code None
[2024-12-19T09:19:12.084+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=101, status='terminated', exitcode=1, started='09:08:46') (101) terminated with exit code 1
[2024-12-19T09:19:12.084+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=212, status='terminated', started='09:12:47') (212) terminated with exit code None
[2024-12-19T09:19:12.085+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=301, status='terminated', started='09:12:49') (301) terminated with exit code None
[2024-12-19T09:19:12.085+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=202, status='terminated', started='09:12:47') (202) terminated with exit code None
[2024-12-19T09:19:12.180+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=313, status='terminated', started='09:12:49') (313) terminated with exit code None
[2024-12-19T09:19:12.273+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=1695, status='terminated', started='09:19:09') (1695) terminated with exit code None
[2024-12-19T09:19:12.274+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=289, status='terminated', started='09:12:48') (289) terminated with exit code None
[2024-12-19T09:19:12.368+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=351, status='terminated', started='09:12:50') (351) terminated with exit code None
[2024-12-19T09:19:12.542+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=333, status='terminated', started='09:12:50') (333) terminated with exit code None
[2024-12-19T09:19:12.768+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=203, status='terminated', started='09:12:47') (203) terminated with exit code None
[2024-12-19T09:19:12.768+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=181, status='terminated', started='09:12:47') (181) terminated with exit code None
[2024-12-19T09:19:12.769+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=279, status='terminated', started='09:12:47') (279) terminated with exit code None
[2024-12-19T09:19:12.769+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=182, status='terminated', started='09:12:47') (182) terminated with exit code None
[2024-12-19T09:19:12.769+0900] {process_utils.py:79} INFO - Process psutil.Process(pid=172, status='terminated', started='09:12:47') (172) terminated with exit code None
