[2024-12-20T14:01:50.872+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [queued]>
[2024-12-20T14:01:50.882+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [queued]>
[2024-12-20T14:01:50.882+0900] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2024-12-20T14:01:50.901+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-18 15:00:00+00:00
[2024-12-20T14:01:50.906+0900] {standard_task_runner.py:57} INFO - Started process 13772 to run task
[2024-12-20T14:01:50.909+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'scheduled__2024-12-18T15:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpwu8hsvnv']
[2024-12-20T14:01:50.912+0900] {standard_task_runner.py:85} INFO - Job 10: Subtask post_crawl
[2024-12-20T14:01:50.956+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl scheduled__2024-12-18T15:00:00+00:00 [running]> on host 885d0f0d454c
[2024-12-20T14:01:51.054+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T15:00:00+00:00'
[2024-12-20T14:01:51.056+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-20 14:01:51
[2024-12-20T14:01:55.152+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-20T14:01:55.275+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T14:01:55.464+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T14:01:55.560+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver] found in cache
[2024-12-20T14:01:55.613+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1969, in post_main
    jumpit_crawling()
  File "/code/plugins/post_crawling.py", line 171, in jumpit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x55cb2e03a8fa <unknown>
#1 0x55cb2db4bd20 <unknown>
#2 0x55cb2db894c7 <unknown>
#3 0x55cb2db83e8f <unknown>
#4 0x55cb2db7ef96 <unknown>
#5 0x55cb2dbcad86 <unknown>
#6 0x55cb2dbca3d6 <unknown>
#7 0x55cb2dbbe893 <unknown>
#8 0x55cb2db8d30d <unknown>
#9 0x55cb2db8e32e <unknown>
#10 0x55cb2e00700b <unknown>
#11 0x55cb2e00af97 <unknown>
#12 0x55cb2dff371c <unknown>
#13 0x55cb2e00bb17 <unknown>
#14 0x55cb2dfd86cf <unknown>
#15 0x55cb2e0296b8 <unknown>
#16 0x55cb2e029880 <unknown>
#17 0x55cb2e039776 <unknown>
#18 0x7fc085f3aea7 start_thread

[2024-12-20T14:01:55.625+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241218T150000, start_date=20241220T050150, end_date=20241220T050155
[2024-12-20T14:01:55.637+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task post_crawl (Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x55cb2e03a8fa <unknown>
#1 0x55cb2db4bd20 <unknown>
#2 0x55cb2db894c7 <unknown>
#3 0x55cb2db83e8f <unknown>
#4 0x55cb2db7ef96 <unknown>
#5 0x55cb2dbcad86 <unknown>
#6 0x55cb2dbca3d6 <unknown>
#7 0x55cb2dbbe893 <unknown>
#8 0x55cb2db8d30d <unknown>
#9 0x55cb2db8e32e <unknown>
#10 0x55cb2e00700b <unknown>
#11 0x55cb2e00af97 <unknown>
#12 0x55cb2dff371c <unknown>
#13 0x55cb2e00bb17 <unknown>
#14 0x55cb2dfd86cf <unknown>
#15 0x55cb2e0296b8 <unknown>
#16 0x55cb2e029880 <unknown>
#17 0x55cb2e039776 <unknown>
#18 0x7fc085f3aea7 start_thread
; 13772)
[2024-12-20T14:01:55.680+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T14:01:55.704+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
