[2024-12-19T17:12:30.486+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:10:39+00:00 [queued]>
[2024-12-19T17:12:30.498+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:10:39+00:00 [queued]>
[2024-12-19T17:12:30.499+0900] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-12-19T17:12:30.512+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-19 08:10:39+00:00
[2024-12-19T17:12:30.516+0900] {standard_task_runner.py:57} INFO - Started process 432 to run task
[2024-12-19T17:12:30.519+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-19T08:10:39+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmpqordxj2n']
[2024-12-19T17:12:30.521+0900] {standard_task_runner.py:85} INFO - Job 5: Subtask post_crawl
[2024-12-19T17:12:30.562+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-19T08:10:39+00:00 [running]> on host 3a17ccfe541c
[2024-12-19T17:12:30.630+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T08:10:39+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T08:10:39+00:00'
[2024-12-19T17:12:30.631+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-19 17:12:30
[2024-12-19T17:12:30.715+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:12:30.774+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:30.853+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:30.924+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:12:31.265+0900] {logging_mixin.py:151} INFO - 점핏 종료 시간: 2024-12-19 17:12:31
[2024-12-19T17:12:41.275+0900] {logging_mixin.py:151} INFO - 원티드 시작 시간: 2024-12-19 17:12:41
[2024-12-19T17:12:41.285+0900] {credentials.py:1254} INFO - Found credentials in shared credentials file: /code/.aws/credentials
[2024-12-19T17:12:41.551+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:12:41.614+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:45.699+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:45.785+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:12:46.042+0900] {logging_mixin.py:151} INFO - 원티드 종료 시간: 2024-12-19 17:12:46
[2024-12-19T17:12:46.042+0900] {logging_mixin.py:151} INFO - 인크루트 시작 시간: 2024-12-19 17:12:46
[2024-12-19T17:12:46.702+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-19T17:12:46.767+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:46.842+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-19T17:12:46.915+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-19T17:12:46.990+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1942, in post_main
    incruit_crawling()
  File "/code/plugins/post_crawling.py", line 623, in incruit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x564e197958fa <unknown>
#1 0x564e192a6d20 <unknown>
#2 0x564e192de438 <unknown>
#3 0x564e192d9f96 <unknown>
#4 0x564e19325d86 <unknown>
#5 0x564e193253d6 <unknown>
#6 0x564e19319893 <unknown>
#7 0x564e192e830d <unknown>
#8 0x564e192e932e <unknown>
#9 0x564e1976200b <unknown>
#10 0x564e19765f97 <unknown>
#11 0x564e1974e71c <unknown>
#12 0x564e19766b17 <unknown>
#13 0x564e197336cf <unknown>
#14 0x564e197846b8 <unknown>
#15 0x564e19784880 <unknown>
#16 0x564e19794776 <unknown>
#17 0x7fae42c0bea7 start_thread

[2024-12-19T17:12:46.998+0900] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241219T081039, start_date=20241219T081230, end_date=20241219T081246
[2024-12-19T17:12:47.010+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task post_crawl (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x564e197958fa <unknown>
#1 0x564e192a6d20 <unknown>
#2 0x564e192de438 <unknown>
#3 0x564e192d9f96 <unknown>
#4 0x564e19325d86 <unknown>
#5 0x564e193253d6 <unknown>
#6 0x564e19319893 <unknown>
#7 0x564e192e830d <unknown>
#8 0x564e192e932e <unknown>
#9 0x564e1976200b <unknown>
#10 0x564e19765f97 <unknown>
#11 0x564e1974e71c <unknown>
#12 0x564e19766b17 <unknown>
#13 0x564e197336cf <unknown>
#14 0x564e197846b8 <unknown>
#15 0x564e19784880 <unknown>
#16 0x564e19794776 <unknown>
#17 0x7fae42c0bea7 start_thread
; 432)
[2024-12-19T17:12:47.042+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-19T17:12:47.060+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
