[2024-12-20T16:47:25.016+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T05:22:51+00:00 [queued]>
[2024-12-20T16:47:25.024+0900] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T05:22:51+00:00 [queued]>
[2024-12-20T16:47:25.024+0900] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2024-12-20T16:47:25.038+0900] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): post_crawl> on 2024-12-20 05:22:51+00:00
[2024-12-20T16:47:25.042+0900] {standard_task_runner.py:57} INFO - Started process 17324 to run task
[2024-12-20T16:47:25.044+0900] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_crawling_to_db', 'post_crawl', 'manual__2024-12-20T05:22:51+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_crawling_to_db.py', '--cfg-path', '/tmp/tmp2wgveq5v']
[2024-12-20T16:47:25.048+0900] {standard_task_runner.py:85} INFO - Job 6: Subtask post_crawl
[2024-12-20T16:47:25.088+0900] {task_command.py:415} INFO - Running <TaskInstance: dag_crawling_to_db.post_crawl manual__2024-12-20T05:22:51+00:00 [running]> on host e792396a0fea
[2024-12-20T16:47:25.169+0900] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_crawling_to_db' AIRFLOW_CTX_TASK_ID='post_crawl' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T05:22:51+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T05:22:51+00:00'
[2024-12-20T16:47:25.170+0900] {logging_mixin.py:151} INFO - 점핏 시작 시간: 2024-12-20 16:47:25
[2024-12-20T16:47:25.261+0900] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-12-20T16:47:25.322+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T16:47:25.421+0900] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-12-20T16:47:25.495+0900] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/131.0.6778.204/chromedriver-linux64/chromedriver] found in cache
[2024-12-20T16:47:25.527+0900] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/code/plugins/post_crawling.py", line 1969, in post_main
  File "/code/plugins/post_crawling.py", line 171, in jumpit_crawling
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x560f0b4088fa <unknown>
#1 0x560f0af19d20 <unknown>
#2 0x560f0af574c7 <unknown>
#3 0x560f0af51e8f <unknown>
#4 0x560f0af4cf96 <unknown>
#5 0x560f0af98d86 <unknown>
#6 0x560f0af983d6 <unknown>
#7 0x560f0af8c893 <unknown>
#8 0x560f0af5b30d <unknown>
#9 0x560f0af5c32e <unknown>
#10 0x560f0b3d500b <unknown>
#11 0x560f0b3d8f97 <unknown>
#12 0x560f0b3c171c <unknown>
#13 0x560f0b3d9b17 <unknown>
#14 0x560f0b3a66cf <unknown>
#15 0x560f0b3f76b8 <unknown>
#16 0x560f0b3f7880 <unknown>
#17 0x560f0b407776 <unknown>
#18 0x7f59080ddea7 start_thread

[2024-12-20T16:47:25.537+0900] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_crawling_to_db, task_id=post_crawl, execution_date=20241220T052251, start_date=20241220T074725, end_date=20241220T074725
[2024-12-20T16:47:25.556+0900] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task post_crawl (Message: session not created
from disconnected: unable to connect to renderer
Stacktrace:
#0 0x560f0b4088fa <unknown>
#1 0x560f0af19d20 <unknown>
#2 0x560f0af574c7 <unknown>
#3 0x560f0af51e8f <unknown>
#4 0x560f0af4cf96 <unknown>
#5 0x560f0af98d86 <unknown>
#6 0x560f0af983d6 <unknown>
#7 0x560f0af8c893 <unknown>
#8 0x560f0af5b30d <unknown>
#9 0x560f0af5c32e <unknown>
#10 0x560f0b3d500b <unknown>
#11 0x560f0b3d8f97 <unknown>
#12 0x560f0b3c171c <unknown>
#13 0x560f0b3d9b17 <unknown>
#14 0x560f0b3a66cf <unknown>
#15 0x560f0b3f76b8 <unknown>
#16 0x560f0b3f7880 <unknown>
#17 0x560f0b407776 <unknown>
#18 0x7f59080ddea7 start_thread
; 17324)
[2024-12-20T16:47:25.580+0900] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-20T16:47:25.600+0900] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
